language: php

branches:
  only:
    - /.*/

php:
  - 7
  - 7.1
  - 7.2

before_script:
  - composer self-update
  - composer install --no-interaction
  - if [[ $TRAVIS_PHP_VERSION = 7.1 ]] || [[ $TRAVIS_PHP_VERSION = 7.2 ]]; then composer global require --dev phpstan/phpstan:0.9.*; fi

script:
  - mkdir build
  - mkdir test/attachments/dir/dirdept
  - ./vendor/bin/phpcs
  - if [[ $TRAVIS_PHP_VERSION = 7.1 ]] || [[ $TRAVIS_PHP_VERSION = 7.2 ]]; then ~/.composer/vendor/bin/phpstan analyse src/ --level=5; fi
  - ./vendor/bin/phpunit --coverage-clover build/clover.xml

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/clover.xml

sudo: false
